In [ ]:
import os
# download cnsst.py 
# change working directory
os.chdir(r'C:\Users\Downloads')
import cnsst
from cnsst import supervised_CNSST
os.chdir(r'C:\\WINDOWS\\system32')
import numpy as np

# iris
# -----------------------------------------------------------------------------------------
# data arrangement
from sklearn import datasets
iris = datasets.load_iris()
test=iris.data
# initiate clustering
clustering = supervised_CNSST(test, adjuster =1, data_instance =iris , n_clusters= 3, sort_col=False, i_column=None, seed_=1)
clustering.predict(clustering)
# -----------------------------------------------------------------------------------------

In [ ]:
# clustering result
final_labels = clustering.f__labels__.copy()
final_labels

In [ ]:
# calculate ACC 
from sympy.utilities.iterables import multiset_permutations
# checked
def target_permutaion(tar_a):
    '''generate permutation arrays for input array
    parameters:
    -----------------
    tar_a, input array, array, shape (a,)
    
    returns:
    -----------------
    result_fi_, list of permutation arrays, list
    
    exapmle:
    target_permutaion(np.array([1,2,3]))
    output:
    [array([1, 2, 3]),
     array([1, 3, 2]),
     array([2, 1, 3]),
     array([2, 3, 1]),
     array([3, 1, 2]),
     array([3, 2, 1])]
    '''
    basic_arr= np.array(tuple(set(tar_a)))
    per_ = multiset_permutations(basic_arr)
    result_fi_ = []
    while True:
        try:
            tar_ = tar_a.copy()
            tar_per_ = np.array(next(per_))
            ex_target = dict(zip(basic_arr, tar_per_))
            for ind_t in range(0,len(tar_)):
                tar_[ind_t] = ex_target[tar_[ind_t]]
            result_fi_.append(tar_)
        except StopIteration:
            break    
    return result_fi_

def acc_(target_input, predicted_labels, v=0):
    if set(target_input) != set(predicted_labels):
        v_arr = np.array(tuple(set(target_input))) - np.array(tuple(set(predicted_labels)))
        if len(np.unique(v_arr,return_counts=True)[0])==1:
            v = v_arr[0]
        else:
            raise ValueError("adjust target or predicted labels")
    input_ = target_input.copy()
    target_permutaion_ = target_permutaion(input_)
    result_50 = []
    result_eve_ = []
    for i_t_p in target_permutaion_:
        arr_to_ = (i_t_p- v ) - predicted_labels
        tul_0 = np.unique(arr_to_,return_counts=True )
        com_ = tul_0[1][np.where(tul_0[0]==0)].astype(int)
        if len(com_) == 0:
            com_ = np.append(com_,[0],0)
        result_eve_.append(com_[0])
    result_eve_arr = np.array(result_eve_)
    result_50.append(np.max(result_eve_arr)/test.shape[0])
    return result_50

acc_(iris.target.copy(),final_labels)